[supervisord]
nodaemon=true
user=root

[program:aptly-web]
command=aptly serve -listen=:80
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true

[program:aptly-api]
command=aptly api serve -listen=:8080 -no-lock
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true
